In [1]:
import duckdb
import pyarrow as pa
import pyarrow.dataset as ds
import pyarrow.parquet as pq
from tqdm import tqdm

In [2]:
import os

os.getcwd()

'/home/flavio/repositories/lstk-dataset/notebooks'

In [3]:
authors_ds = ds.dataset("../data/authors.parquet")
# authors_db = duckdb.arrow(authors_ds)

In [4]:
affiliations_ds = ds.dataset("../data/affiliations.parquet")

In [30]:
with duckdb.connect() as con:
    con.execute("SET threads=1")
    con.execute("select setseed(0.23)")
    mydf = con.execute("select * from affiliations_ds order by random() limit 10").fetchdf()

mydf

     AuthorId  AffiliationId  Year Iso3166Code   Latitude   Longitude
0  2233600571      170201317  2006          US  40.444565  -79.953280
1   240569416        9341345  2008          DE  53.836940   10.705830
2   322019271       17866349  2009          FR  43.604440    1.443890
3  2153046031      165735259  2001          JP  36.430280  139.045000
4  2124545317      130343225  2003          MY   2.999170  101.707779
5  2673673140      116953780  2011          CN  31.282700  121.506600
6  2144725316      177725633  2003          HK  22.419720  114.206795
7  1569013815      113456305  2013          DE  53.228890   10.401110
8  2130267246     1334661382  2004          FR  48.838060    2.582420
9  2376908206      899635006  2014          FR  45.187780    5.726944

In [31]:
with duckdb.connect() as con:
    con.execute("SET threads=1")
    con.execute("select setseed(0.23)")
    mydf = con.execute("select * from affiliations_ds order by random() limit 10").fetchdf()

mydf

     AuthorId  AffiliationId  Year Iso3166Code   Latitude   Longitude
0  2233600571      170201317  2006          US  40.444565  -79.953280
1   240569416        9341345  2008          DE  53.836940   10.705830
2   322019271       17866349  2009          FR  43.604440    1.443890
3  2153046031      165735259  2001          JP  36.430280  139.045000
4  2124545317      130343225  2003          MY   2.999170  101.707779
5  2673673140      116953780  2011          CN  31.282700  121.506600
6  2144725316      177725633  2003          HK  22.419720  114.206795
7  1569013815      113456305  2013          DE  53.228890   10.401110
8  2130267246     1334661382  2004          FR  48.838060    2.582420
9  2376908206      899635006  2014          FR  45.187780    5.726944

In [15]:
with duckdb.connect() as con:
    chunk_size = 50_000
    query = con.execute("""
        WITH ranked_duplicates AS (
            SELECT 
                *,
                ROW_NUMBER() OVER (
                    PARTITION BY AuthorId, Year
                    ORDER BY random()
                ) as row_num
            FROM affiliations_ds
        )
        SELECT * FROM authors_ds
        LEFT JOIN (
            SELECT affiliations.AuthorId, 
            Iso3166Code as Iso3166Code_FirstAffiliation
            FROM ranked_duplicates AS affiliations 
            INNER JOIN (
              SELECT AuthorId, 
              MIN(Year) AS first_affiliation_year
              FROM ranked_duplicates 
              GROUP BY AuthorId
            ) as b 
            ON (affiliations.authorid=b.authorid 
                and affiliations.year=b.first_affiliation_year
            )
            WHERE row_num = 1
        )
        USING (AuthorId) 
    """)
    record_batch_reader = query.fetch_record_batch(chunk_size)
    first_chunk = next(record_batch_reader)
    with pq.ParquetWriter("../data/mytest.parquet", first_chunk.schema) as writer:
        writer.write(first_chunk)
        for i, chunk in tqdm(enumerate(record_batch_reader), desc="Processing batches"):
            writer.write(chunk)

Processing batches: 21it [00:00, 32.34it/s]

## We also need to get rid of duplicates in affiliation table

In [ ]:
affiliations_ds = ds.dataset("../data/affiliations.parquet")